name: Deploy ilearn to GCP

on:
  release:
    types: [created]
  push:
    branches:
      - "master"

jobs:

  deployToGCP:
    name: Deploy ilearn to GCP
    runs-on: ubuntu-latest
    steps:
      - name: connect to GCP with ssh
        uses: appleboy/ssh-action@master 
        with:
          host: 35.232.212.107
          port: 22
          username: mahmoudashraf11179
          key: ${{ secrets.GCP_ILEARN }}
          passphrase: ${{ secrets.GCP_PASS }}
          script: |
            cd Schooly
            git pull origin master
            yarn run build:all
            docker stop schooly
            docker remove schooly
            docker build -t uptotec/schooly:latest .
            docker run -p 4000:4000 --net="host" --restart on-failure -d --name schooly uptotec/schooly:latest

