name: Deploy ilearn to GCP

on:
  push:
    tags:
      - "*"

jobs:

  deployToGCP:
    name: Deploy ilearn to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Run build commands
        uses: appleboy/ssh-action@master 
        with:
          host: 35.232.212.107
          port: 22
          command_timeout: 200m
          username: mahmoudashraf11179
          key: ${{ secrets.GCP_ILEARN }}
          passphrase: ${{ secrets.GCP_PASS }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            eval $(ssh-agent -s)
            ssh-add github_key
            cd Schooly/
            git pull origin master
            yarn install
            yarn run build:all
            docker stop schooly
            docker rm schooly
            docker build -t uptotec/schooly:1.0.0 .
            docker run -p 4000:4000 --net="host" --restart on-failure -d --name schooly uptotec/schooly:1.0.0

